title: Al Tayyab Bakhsh
#logo: /assets/img/headshot_circle.png
description: Al Tayyab Bakhsh Office Administrator ğŸ“ | Data Science & Analytics Learner ğŸ“Š | AI and Blockchain Enthusiast âš¡ | Dedicated to Applying Data Science for Real-World Impact ğŸŒ
theme: jekyll-theme-minimal
